var movieInformation = 	[ 
							{ 
								"Id": 0,
								"Name": "Shooter",
								"NoSeason": 3,
								"Duration": "0",
								"Genre": ["Accion", "Bestseller", "TV"],
								"Age": "16+",
								"Match": "96",
								"Features": ["Poco convencional", "Realista"],
								"backgroundImage":"",
								"MiniImage": "movie_1.png",
								"Description": "Un francotirador, marine retirado, regresa a la acción para defender al presidente, pero pronto descubre que le tendieron una trampa.",
								"Cast": ["Ryan Phillippe", "Omar Epps", "David Marciano"],
								"Director": "Netflix",
								"isBanner": 0
							},
							{
								"Id": 1,
								"Name": "Better Call Saul",
								"NoSeason": 4,
								"Duration": "0",
								"Genre": ["Dramas de Tv", "Comedias de TV", "Programas de EEUU"],
								"Age": "16+",
								"Match": "88",
								"Features": ["Poco convencional", "Realista"],
								"backgroundImage":"",
								"MiniImage": "movie_2.png",
								"Description": "Jimmy se pone seductor para una entrevista de trabajo, mientras Gus se preocupa por la salud de Héctor Salamanca. Harta de todo, Kim se descarga con Howard.",
								"Cast": ["Bob Odenkirk", "Jonathan Banks", "Rhea Seehorn"],
								"Director": "Vince Gilligan, Peter Gould",
								"isBanner": 0
							},
							{
								"Id": 2,
								"Name": "Perdidos en el espacio",
								"NoSeason": 1,
								"Duration": "0",
								"Genre": ["TV para ver en familia", "Dramas de TV", "Programas de EEUU"],
								"Age": "7+",
								"Match": "83",
								"Features": ["Imaginativo", "Intrigrante"],
								"backgroundImage":"",
								"MiniImage": "movie_3.png",
								"Description": "Tras aterrizar de emergencia en un planeta desconocido y plagado de peligros ocultos, los Robinson luchan contra todos los obstáculos para sobrevivir y escapar.",
								"Cast": ["Molly Parker", "Toby Stephens", "Maxwell Jenkins"],
								"Director": "Netflix",
								"isBanner": 0
							},
							{
								"Id": 3,
								"Name": "Las Cintas de Ted Bundy",
								"NoSeason": 1,
								"Duration": "0",
								"Genre": ["TV sobre crimen", "Programas de EEUU", "Docuseries", "Documentales"],
								"Age": "16+",
								"Match": "90",
								"Features": ["Provocador"],
								"backgroundImage":"bundy_Back.png",
								"MiniImage": "movie_4.png",
								"Description": "El juicio contra Bundy se transforma en un circo de locos. En la hora final, el asesino hace una jugada desesperada para evitar la ejecución.",
								"Cast": "",
								"Director": "Joe Berlinger",
								"isBanner": 0
							},
							{
								"Id": 4,
								"Name": "Punisher",
								"NoSeason": 2,
								"Duration": "0",
								"Genre": ["Progrmas basados en comic", "TV sobre crimen", "Progrmas de EEUU", "TV de accion y aventuras"],
								"Age": "16+",
								"Match": "90",
								"Features": ["Realista", "Violento"],
								"backgroundImage":"",
								"MiniImage": "movie_5.png",
								"Description": "El exmarine Frank Castle vive como un espectro en el infierno que el mismo creó para vengar a su familia. La furia late en sus ojos. La justicia está en sus manos.",
								"Cast": ["Jon Bernthal", "Ben Barnes", "Amber Rose Revah"],
								"Director": "Steve Lightfoot",
								"isBanner": 0
							},
							{
								"Id": 5,
								"Name": "Bright",
								"NoSeason": 0,
								"Duration": "1h 7min",
								"Genre": ["Accion y aventuras", "Thrillers de accion", "Accion y aventuras criminales"],
								"Age": "16+",
								"Match": "80",
								"Features": ["Realista" , "Violento"],
								"backgroundImage":"",
								"MiniImage": "movie_6.png",
								"Description": "En Los&nbsp;Ángeles, en medio de tensiones territoriales entre especies, un policía humano y su compañero orco encuentran un poderoso objeto. La guerra profetizada comenzó.",
								"Cast": ["Will Smith", "Joel Edgerton", "Noomi Rapace"],
								"Director": "David Ayer",
								"isBanner": 0
							},
							{
								"Id": 6,
								"Name": "Scandal",
								"NoSeason": 7,
								"Duration": "0",
								"Genre": ["TV sobre politica", "Dramas de TV", "TV sobre crimen"],
								"Age": "16+",
								"Match": "92",
								"Features": ["Sombrio", "Intrigrante", "Emocionante"],
								"backgroundImage":"background_HL.png",
								"MiniImage": "movie_7.png",
								"Description": "Un equipo poderoso de abogados en Washington D. C. desaparece escándalos al mismo tiempo que maneja las crisis del Gobierno y sus propios problemas.",
								"Cast": ["Kerry Washington", "Columbus Short", "Darby Stanchfield"],
								"Director": "Shonda Rhimes",
								"isBanner": 1
							}
						];
